/**
 * API Legislação
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Compromisso {

    private dataCriacao: Date;
  
    constructor(
        private titulo: string,
        private dataInicio: string,
        private dataFim: string,
        private status: string,
        private descricao: string,
        private _id:  string
    ) {
      this.dataCriacao = new Date();
    }
  
    getTitulo(): string {
      return this.titulo;
    }
}